// @ts-check
import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';

test('Hand-drawn BV and CV screens keep separate navigation and exact controls',async t=>{
  const bundled=await build({stdin:{contents:"import {startApp} from './src/app.js';import {store} from './src/state/store.js';import {navigate} from './src/router.js';window.testApi={store,navigate};startApp();",resolveDir:process.cwd()},bundle:true,write:false,platform:'browser',format:'iife',define:{'import.meta.env':'{}'}});
  const dom=new JSDOM('<div id="app"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>dom.window.close());const w=dom.window,d=w.document;w.structuredClone=structuredClone;w.scrollTo=()=>{};w.confirm=()=>true;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.eval(bundled.outputFiles[0].text);
  async function until(check){for(let i=0;i<150;i++){if(check())return;await new Promise(r=>setTimeout(r,20));}throw new Error('Screen timeout: '+d.body.textContent.slice(0,500));}
  const click=selector=>{const node=d.querySelector(selector);assert.ok(node,selector);node.click();};
  await until(()=>d.querySelectorAll('[data-role]').length===3);assert.ok(d.querySelector('[data-role="invite"]'));
  click('[data-role="business"]');await until(()=>d.querySelector('#google-login'));click('#google-login');await until(()=>d.querySelector('#business-form'));
  assert.equal(d.querySelector('#business-form [name="email"]'),null);assert.match(d.body.textContent,/E-mail Google:.*andrei@demo.ro/);assert.ok(d.querySelector('#business-details-sign-out'));assert.equal(d.querySelector('#business-details-sign-out').textContent,'Deconectare');
  const businessName=/** @type {HTMLInputElement} */(d.querySelector('#business-form [name="name"]'));businessName.value='  Salon Nou  ';businessName.dispatchEvent(new w.Event('focusout',{bubbles:true}));assert.equal(businessName.value,'Salon Nou');
  assert.equal(d.querySelectorAll('.bottom-nav__item').length,0);
  assert.equal(d.querySelector('[data-route="/business/invite"]'),null);
  await w.testApi.store.set({business:{id:'atelier-luna',name:'Atelier Luna',is_owner:true},demoAccess:{source:'developer',calendarLimit:10,expiresAt:'infinity'},demoCalendars:[{id:'demo-calendar-1',name:'Manichiură semipermanentă',is_active:true},{id:'demo-calendar-2',name:'Pedichiură',is_active:true}]});
  w.testApi.navigate('/business/home');await until(()=>d.querySelector('.draw-chart'));assert.match(d.body.textContent,/Scanează codul QR/);assert.match(d.body.textContent,/Invită pe cineva \(adresa de mail\)/);assert.equal(d.querySelector('#home-invite [name="email"]').getAttribute('placeholder'),'coleg@gmail.com');assert.ok(d.querySelector('[data-invitee-delete="demo-staff"]'));assert.equal(d.querySelectorAll('.bottom-nav__item').length,4);assert.equal(d.querySelector('.bottom-nav__item:last-child span:last-child').textContent,'Cont');assert.ok(d.querySelector('[data-route="/business/notifications"] .notification-dot'));assert.equal(d.querySelectorAll('.draw-chart__date').length,7);assert.equal(d.querySelectorAll('.draw-chart__count').length,7);assert.ok(d.querySelector('[data-report-mode="week"].is-active'));click('[data-report-mode="day"]');await until(()=>d.querySelector('.draw-chart--day'));assert.equal(d.querySelectorAll('.draw-chart__item').length,1);assert.ok(d.querySelector('[data-week="-1"]'));assert.ok(d.querySelector('[data-week="1"]'));
  const inviteEmail=/** @type {HTMLInputElement} */(d.querySelector('#home-invite [name="email"]'));inviteEmail.value='  colegnou@gmail.com  ';d.querySelector('#home-invite').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await until(()=>d.querySelector('.toast')?.textContent.includes('Invitație trimisă.'));
  await w.testApi.store.set({business:{id:'atelier-luna',name:'Atelier Luna',is_owner:false}});w.testApi.navigate('/business/home');await until(()=>d.querySelector('#home-invite')===null&&d.body.textContent.includes('coleg@demo.ro'));assert.match(d.body.textContent,/Membri/);assert.equal(d.querySelector('[data-invitee-delete]'),null);assert.equal(d.querySelector('[data-route="/business/team"]'),null);assert.doesNotMatch(d.body.textContent,/Vezi echipa/);w.testApi.navigate('/business/calendar');await until(()=>d.querySelector('[data-calendar-delete]'));assert.ok(d.querySelector('[data-calendar-delete]'));
  await w.testApi.store.set({business:{id:'atelier-luna',name:'Atelier Luna',is_owner:true}});
  w.testApi.navigate('/business/calendar');await until(()=>d.querySelector('#calendar-add'));assert.equal(d.querySelectorAll('[data-calendar-view]').length,2);assert.equal(d.querySelectorAll('[data-calendar-delete]').length,2);assert.ok(d.querySelector('.app-shell--with-nav'));click('[data-calendar-delete="demo-calendar-1"]');await until(()=>d.querySelector('.popup[role="dialog"]'));click('.popup .button--danger');await until(()=>d.querySelector('.toast--error'));assert.match(d.querySelector('.toast').textContent,/are programări/);assert.ok(d.querySelector('.toast').parentElement.classList.contains('app-message-layer'));click('[data-calendar-delete="demo-calendar-2"]');await until(()=>d.querySelector('.popup[role="dialog"]'));click('.popup .button--danger');await until(()=>d.querySelectorAll('[data-calendar-view]').length===1);assert.equal(d.querySelector('[data-calendar-delete="demo-calendar-2"]'),null);click('[data-calendar-view]');await until(()=>d.querySelector('.weekday-tabs'));assert.equal(d.querySelectorAll('.calendar-view-head .weekday-tabs button small').length,7);assert.match(d.querySelector('.calendar-view-head .weekday-tabs button small').textContent,/\d{2}\.\d{2}/);assert.ok(d.querySelector('.draw-fab'));
  click('.draw-fab');await until(()=>d.querySelector('#event-settings'));assert.equal(d.querySelector('textarea[name="name"]'),null);assert.equal(d.querySelectorAll('[name="duration"] option').length,11);assert.equal(d.querySelectorAll('.weekday-tabs input').length,7);assert.ok(d.querySelector('[name="startTime"]'));assert.ok(d.querySelector('[name="endTime"]'));
  w.testApi.navigate('/business/notifications');await until(()=>d.querySelector('#notification-calendar'));assert.ok(d.querySelector('[data-status="confirmed"]'));assert.ok(d.querySelector('[data-status="rejected"]'));
  w.testApi.navigate('/profile');await until(()=>d.querySelector('#sign-out'));assert.match(d.body.textContent,/Licență activă · fără expirare/);assert.equal(d.querySelector('[data-plan="small"]'),null);assert.equal(d.querySelector('[data-plan="large"]'),null);assert.match(d.body.textContent,/Termeni și condiții/);assert.match(d.body.textContent,/Politica de confidențialitate/);assert.ok(d.querySelector('.account-modern--business'));assert.equal(d.querySelectorAll('.account-modern__tile').length,2);assert.ok(d.querySelector('.account-glass-card'));
  w.testApi.navigate('/business/plans');await until(()=>d.querySelector('[data-plan="large"].is-selected'));click('[data-plan="small"]');assert.ok(d.querySelector('[data-plan="large"].is-selected'));
  await w.testApi.store.set({demoAccess:{source:'demo',calendarLimit:10,expiresAt:new Date(Date.now()-60000).toISOString()}});w.testApi.navigate('/business/home');await until(()=>d.body.textContent.includes('Alege planul'));assert.equal(d.querySelector('.draw-chart'),null);assert.equal(d.querySelectorAll('.bottom-nav__item').length,0);
  await w.testApi.store.set({role:'customer',customerProfileComplete:true,selectedBusinessId:null});w.testApi.navigate('/customer/login');await until(()=>d.querySelector('#company-search'));assert.equal(d.querySelector('#customer-profile-form'),null);assert.equal(d.querySelectorAll('.bottom-nav__item').length,4);assert.ok(d.querySelector('[data-route="/customer/notifications"]'));w.testApi.navigate('/profile');await until(()=>d.querySelector('.account-modern--customer'));assert.equal(d.querySelectorAll('.account-modern__tile').length,2);assert.equal(d.querySelector('[data-plan]'),null);w.testApi.navigate('/customer/login');await until(()=>d.querySelector('#company-search'));
  const search=/** @type {HTMLInputElement} */(d.querySelector('#company-search'));search.value='Bar';search.dispatchEvent(new w.Event('input',{bubbles:true}));await until(()=>d.querySelectorAll('[data-company]').length===1);assert.match(d.body.textContent,/Barber Eleven/);search.value='leven';search.dispatchEvent(new w.Event('input',{bubbles:true}));await until(()=>d.querySelectorAll('[data-company]').length===0);
  search.value='At';search.dispatchEvent(new w.Event('input',{bubbles:true}));await until(()=>d.querySelector('[data-company]'));click('[data-company]');await until(()=>d.querySelector('#service-select'));assert.equal(d.querySelectorAll('#service-select').length,1);assert.ok(d.querySelector('#service-duration[readonly]'));const service=/** @type {HTMLSelectElement} */(d.querySelector('#service-select'));service.value='manichiura';service.dispatchEvent(new w.Event('change',{bubbles:true}));await until(()=>d.querySelector('#service-duration').value==='60 min');
  w.testApi.navigate('/customer/notifications');await until(()=>d.querySelector('#notification-form'));assert.equal(d.querySelector('#notification-calendar'),null);assert.match(d.body.textContent,/programările aprobate/);assert.equal(d.querySelectorAll('.bottom-nav__item').length,4);
  w.testApi.navigate('/customer/bookings');await until(()=>d.querySelector('[data-booking-qr]'));assert.match(d.body.textContent,/Atelier Luna/);assert.match(d.body.textContent,/În așteptare/);assert.ok(d.querySelector('.booking-status--pending'));assert.ok(d.querySelector('.booking-status--confirmed'));assert.equal(d.querySelectorAll('.bottom-nav__item').length,4);click('[data-booking-qr]');await until(()=>w.location.hash.includes('/customer/booking-qr?booking=b1'));assert.doesNotMatch(d.body.textContent,/Selectează o programare din lista ta/);
  await w.testApi.store.set({customerProfileComplete:false});w.testApi.navigate('/customer/profile-setup');await until(()=>d.querySelector('#customer-setup-sign-out'));click('#customer-setup-sign-out');await until(()=>d.querySelectorAll('[data-role]').length===3);assert.equal(w.testApi.store.get().user,null);
});

test('Pre-enrollment exits and legal pages use the final Romanian labels',async()=>{
  const files=await Promise.all(['src/screens/enrollment.js','src/screens/customer-profile.js','src/screens/team.js','src/screens/profile.js','public/terms.html'].map(path=>import('node:fs/promises').then(({readFile})=>readFile(new URL('../'+path,import.meta.url),'utf8'))));
  const source=files.slice(0,4).join('\n');
  for(const id of ['business-details-sign-out','verification-sign-out','customer-setup-sign-out','invite-sign-out'])assert.match(source,new RegExp(id));
  assert.doesNotMatch(source,/Schimbă contul Google|>\s*(?:Sign out|Log out)\s*</i);
  assert.match(source,/Deconectare/);
  assert.doesNotMatch(files[4],/De completat înainte de publicare/i);
  assert.match(files[3],/Politica de confidențialitate/);
});
