// @ts-check
import {store} from '../state/store.js';
import {calendars,rpc} from '../services/access.js';
import {listPendingBookingRequests,getCalendarNotificationMinutes,setCalendarNotificationMinutes} from '../services/businesses.js';
import {escapeHtml} from '../ui/dom.js';
import {page,bindBack,loadingButton,toast} from '../ui/layout.js';

export async function notificationsScreen(root,role){
  if(role!=='business'){root.innerHTML=page({title:'Notificări',nav:'customer',content:''});bindBack(root);return;}
  const business=store.get().business;const params=new URLSearchParams(window.location.hash.split('?')[1]||'');const selected=params.get('calendar')||'';
  const [requests,list]=await Promise.all([listPendingBookingRequests(business.id),calendars(business.id)]);
  const minutes=selected?await getCalendarNotificationMinutes(selected):15;
  root.innerHTML=page({title:'Notificări',nav:'business',active:'notifications',content:`<section class="draw-section"><h1>Cereri de programare</h1><div class="request-list">${requests.length?requests.map(item=>`<article><span><strong>${escapeHtml(item.customer)}</strong><small>${escapeHtml(item.service)} · ${escapeHtml(item.time)}-${escapeHtml(item.endTime)}</small></span><span><button class="button button--primary button--compact" data-request="${escapeHtml(item.id)}" data-status="confirmed">Aprobă</button><button class="button button--secondary button--compact" data-request="${escapeHtml(item.id)}" data-status="rejected">Respinge</button></span></article>`).join(''):'<p class="empty-note">Nu există cereri în așteptare.</p>'}</div></section><section class="draw-section"><label>Calendar<select id="notification-calendar"><option value="">Alege calendarul</option>${list.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===selected?'selected':''}>${escapeHtml(item.name)}</option>`).join('')}</select></label></section>${selected?`<section class="draw-section draw-section--center"><h1>${escapeHtml(list.find(item=>item.id===selected)?.name||'')}</h1><form class="draw-inline-form" id="calendar-reminder"><label>Notificare înainte de programare<select name="minutes">${Array.from({length:29},(_,index)=>index+2).map(value=>`<option value="${value}" ${Number(minutes)===value?'selected':''}>${value} minute</option>`).join('')}</select></label><button class="button button--primary">Salvează</button></form></section>`:''}`});
  bindBack(root);root.querySelector('#notification-calendar')?.addEventListener('change',event=>{window.location.hash=`/business/notifications?calendar=${/** @type {HTMLSelectElement} */(event.currentTarget).value}`;});
  root.querySelectorAll('[data-request]').forEach(button=>button.addEventListener('click',async()=>{try{loadingButton(button,true);await rpc('set_booking_status',{p_booking_id:button.getAttribute('data-request'),p_status:button.getAttribute('data-status')});await notificationsScreen(root,'business');toast(root,button.getAttribute('data-status')==='confirmed'?'Programarea a fost aprobată.':'Programarea a fost respinsă.');}catch(error){loadingButton(button,false);toast(root,error.message,'error');}}));
  root.querySelector('#calendar-reminder')?.addEventListener('submit',async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button');try{loadingButton(button,true);await setCalendarNotificationMinutes(selected,Number(new FormData(/** @type {HTMLFormElement} */(event.currentTarget)).get('minutes')));await notificationsScreen(root,'business');toast(root,'Notificarea calendarului a fost salvată.');}catch(error){loadingButton(button,false);toast(root,error.message,'error');}});
}
