-- Rename technical logger action names to short, user-facing actions.
-- PostgreSQL enum value renames also update every existing logger_engine row
-- without deleting or recreating historical logs. Safe to run more than once.

begin;

do $migration$
declare
  v_old text;
  v_new text;
begin
  for v_old,v_new in
    select * from (values
      ('BV_RESOLVE_CURRENT_ACCOUNT_TYPE_AFTER_GOOGLE_AUTHENTICATION','BV_SIGN_IN'),
      ('CV_RESOLVE_CURRENT_ACCOUNT_TYPE_AFTER_GOOGLE_AUTHENTICATION','CV_SIGN_IN'),
      ('BV_READ_CURRENT_BUSINESS_ACCESS_ENTITLEMENT','BV_CHECK_ACCESS'),
      ('BV_REDEEM_COMPLETE_BUSINESS_LICENSE_KEY','BV_ACTIVATE_LICENSE'),
      ('BV_LIST_ACCESSIBLE_BUSINESS_WORKSPACES','BV_VIEW_MY_BUSINESSES'),
      ('BV_LIST_BUSINESS_CALENDARS','BV_VIEW_CALENDARS'),
      ('BV_CREATE_NEW_BUSINESS_CALENDAR','BV_CREATE_CALENDAR'),
      ('BV_DELETE_EMPTY_BUSINESS_CALENDAR','BV_DELETE_CALENDAR'),
      ('BV_READ_BUSINESS_TEAM_MEMBERS_AND_PENDING_INVITATIONS','BV_VIEW_TEAM'),
      ('BV_SEND_NEW_BUSINESS_TEAM_MEMBER_EMAIL_INVITATION','BV_INVITE_TEAM_MEMBER'),
      ('BV_ACCEPT_BUSINESS_TEAM_MEMBER_EMAIL_INVITATION','BV_ACCEPT_TEAM_INVITATION'),
      ('BV_REVOKE_PENDING_BUSINESS_TEAM_MEMBER_INVITATION','BV_CANCEL_TEAM_INVITATION'),
      ('BV_UPDATE_BUSINESS_TEAM_MEMBER_OPERATIONAL_ACCESS','BV_UPDATE_TEAM_MEMBER_ACCESS'),
      ('BV_REMOVE_BUSINESS_TEAM_MEMBER_FROM_TEAM','BV_REMOVE_TEAM_MEMBER'),
      ('CV_SEARCH_ACTIVE_BUSINESSES_BY_NAME','CV_SEARCH_BUSINESS'),
      ('CV_READ_SELECTED_BUSINESS_DETAILS_SERVICES_AND_CALENDARS','CV_VIEW_BUSINESS_DETAILS'),
      ('BV_INITIALIZE_BUSINESS_PRIMARY_CALENDAR_AND_SERVICE','BV_COMPLETE_INITIAL_SETUP'),
      ('BV_READ_APPROVED_BUSINESS_BOOKINGS_FOR_CALENDAR_VIEW','BV_VIEW_CALENDAR_APPOINTMENTS'),
      ('BV_READ_PENDING_BUSINESS_BOOKING_REQUESTS','BV_VIEW_PENDING_APPOINTMENTS'),
      ('BV_READ_ACTIVE_BUSINESS_SERVICES_FOR_CALENDAR','BV_VIEW_CALENDAR_SERVICES'),
      ('BV_CREATE_NEW_BUSINESS_SERVICE_AND_AVAILABILITY','BV_CREATE_SERVICE'),
      ('BV_READ_BUSINESS_CALENDAR_SERVICE_SETTINGS','BV_VIEW_SERVICE_SETTINGS'),
      ('BV_UPDATE_BUSINESS_CALENDAR_SERVICE_SETTINGS','BV_UPDATE_SERVICE_SCHEDULE'),
      ('BV_READ_BUSINESS_CALENDAR_NOTIFICATION_PREFERENCES','BV_VIEW_CALENDAR_REMINDER'),
      ('BV_UPDATE_BUSINESS_CALENDAR_NOTIFICATION_PREFERENCES','BV_UPDATE_CALENDAR_REMINDER'),
      ('BV_READ_APPROVED_BUSINESS_BOOKING_REPORT','BV_VIEW_REPORTS'),
      ('CV_READ_CLIENT_NOTIFICATION_PREFERENCES','CV_VIEW_REMINDER'),
      ('CV_UPDATE_CLIENT_NOTIFICATION_PREFERENCES','CV_UPDATE_REMINDER'),
      ('CV_READ_AVAILABLE_BOOKING_SLOTS_FOR_SELECTED_SERVICE','CV_VIEW_AVAILABLE_APPOINTMENT_TIMES'),
      ('CV_CREATE_NEW_BOOKING_REQUEST','CV_MAKE_APPOINTMENT'),
      ('CV_READ_CURRENT_CLIENT_BOOKINGS','CV_VIEW_MY_APPOINTMENTS'),
      ('CV_READ_CURRENT_CLIENT_PROFILE','CV_VIEW_PROFILE'),
      ('CV_COMPLETE_CURRENT_CLIENT_PROFILE','CV_COMPLETE_PROFILE'),
      ('CV_GENERATE_QR_FOR_CURRENT_CLIENT_RESERVATION','CV_VIEW_APPOINTMENT_QR'),
      ('BV_RESOLVE_SCANNED_CLIENT_RESERVATION_QR','BV_SCAN_APPOINTMENT_QR'),
      ('BV_APPROVE_PENDING_CLIENT_BOOKING_REQUEST','BV_APPROVE_APPOINTMENT'),
      ('BV_REJECT_PENDING_CLIENT_BOOKING_REQUEST','BV_REJECT_APPOINTMENT'),
      ('BV_READ_BUSINESS_ENROLLMENT_STATUS','BV_VIEW_ENROLLMENT_STATUS'),
      ('BV_CHECK_CURRENT_ACCOUNT_PLATFORM_OWNER_PERMISSION','BV_CHECK_ADMIN_ACCESS'),
      ('BV_READ_BUSINESS_ENROLLMENT_LINK_DETAILS','BV_VIEW_ENROLLMENT_REQUEST'),
      ('BV_START_NEW_BUSINESS_ENROLLMENT_REQUEST','BV_SUBMIT_BUSINESS_ENROLLMENT'),
      ('BV_RESEND_BUSINESS_ENROLLMENT_EMAIL_VERIFICATION_CODE','BV_RESEND_ENROLLMENT_EMAIL'),
      ('BV_SEND_BUSINESS_ENROLLMENT_PHONE_VERIFICATION_SMS','BV_SEND_PHONE_VERIFICATION_CODE'),
      ('BV_VERIFY_BUSINESS_ENROLLMENT_PHONE_SMS_CODE','BV_CONFIRM_PHONE_VERIFICATION_CODE'),
      ('BV_CONFIRM_BUSINESS_ENROLLMENT_EMAIL_VERIFICATION_LINK','BV_CONFIRM_ENROLLMENT_EMAIL'),
      ('BV_APPROVE_BUSINESS_ENROLLMENT_REQUEST_BY_PLATFORM_OWNER','BV_APPROVE_BUSINESS_ENROLLMENT'),
      ('BV_REJECT_BUSINESS_ENROLLMENT_REQUEST_BY_PLATFORM_OWNER','BV_REJECT_BUSINESS_ENROLLMENT'),
      ('BV_REGISTER_BUSINESS_ANDROID_PUSH_DEVICE_TOKEN','BV_ENABLE_PUSH_NOTIFICATIONS'),
      ('CV_REGISTER_CLIENT_ANDROID_PUSH_DEVICE_TOKEN','CV_ENABLE_PUSH_NOTIFICATIONS'),
      ('BV_REMOVE_BUSINESS_ANDROID_PUSH_DEVICE_TOKEN_ON_SIGN_OUT','BV_DISABLE_PUSH_NOTIFICATIONS'),
      ('CV_REMOVE_CLIENT_ANDROID_PUSH_DEVICE_TOKEN_ON_SIGN_OUT','CV_DISABLE_PUSH_NOTIFICATIONS'),
      ('BV_SYNCHRONIZE_GOOGLE_PLAY_SUBSCRIPTION_ENTITLEMENT','BV_REFRESH_SUBSCRIPTION')
    ) as mapping(old_value,new_value)
  loop
    if exists(
      select 1
      from pg_type t
      join pg_namespace n on n.oid=t.typnamespace
      join pg_enum e on e.enumtypid=t.oid
      where n.nspname='public'
        and t.typname='logger_action_type'
        and e.enumlabel=v_old
    ) and not exists(
      select 1
      from pg_type t
      join pg_namespace n on n.oid=t.typnamespace
      join pg_enum e on e.enumtypid=t.oid
      where n.nspname='public'
        and t.typname='logger_action_type'
        and e.enumlabel=v_new
    ) then
      execute format(
        'alter type public.logger_action_type rename value %L to %L',
        v_old,
        v_new
      );
    end if;
  end loop;
end
$migration$;

commit;
